import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../components/navbar'
import { useState } from 'react'
import { useConnection, useWallet } from '@solana/wallet-adapter-react'
import {
  LAMPORTS_PER_SOL,
  Transaction,
  PublicKey,
} from '@solana/web3.js'


const Home: NextPage = () => {

  const { connection } = useConnection()
  const { publicKey, sendTransaction } = useWallet()


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <div className='container'>
        <h1>Connected to: {publicKey?.toBase58()}</h1>
      </div>

      <footer></footer>
    </div>
  )
}

export default Home
